[build]
  command = "npm run build"  # Byggkommandot
  publish = "dist"  # Mappen med de byggda filerna

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/.js"
  [headers.values]
    Content-Type = "application/javascript"  # Säkerställer rätt MIME-typ